name: Pl3xMap-Marker
version: '${version}'
main: god.sentix.pl3xmarker.Pl3xMapMarker
api-version: 1.17
depend: [ Pl3xMap ]
authors: [ Sentix ]
description: Simple marker extension for Pl3xMap
website: https://github.com/SentixDev/Pl3xMap-Marker

commands:
  pl3xmarker:

permissions:
  pl3xmarker.marker:
    description: Gives access to /pl3xmarker command
    default: op