name: Pl3xMap-Marker
version: '${project.version}'
main: god.sentix.pl3xmapmarker.Main
api-version: 1.17
authors: [ Sentix ]
description: Simple plugin to add markers on pl3xmap

commands:
  testmarker: